user:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  option:
    size: 80
  image:
    size: 50
    max_size: 5
  id: 
    max_length: 140
page: 
  per_page: 20
